ARG GO_VERSION
ARG PLATFORM

FROM golang:$GO_VERSION

WORKDIR /go/src/github.com/percona/dcos-mongo-tools
COPY . .

RUN apk update && \
    apk add git make upx

RUN make vendor

CMD make test && \
    make && \
    upx bin/mongodb-*-*
