ARG GOLANG_DOCKERHUB_TAG

FROM golang:$GOLANG_DOCKERHUB_TAG

WORKDIR /go/src/github.com/percona/dcos-mongo-tools
COPY . .

RUN apk update && \
    apk add git make upx

RUN make vendor

CMD make test && \
    make && \
    upx bin/mongodb-*-*
