ARG GOLANG_DOCKERHUB_TAG

FROM golang:$GOLANG_DOCKERHUB_TAG

WORKDIR /go/src/github.com/percona/dcos-mongo-tools
COPY . .

RUN apt-get update && \
    apt-get install -y upx-ucl zip && \
    apt-get clean all

CMD make test-full && \
    make && \
    upx bin/* && \
    zip -j bin/dcos-mongo-tools_mongod.zip bin/dcos-mongodb-executor && \
    zip -j bin/dcos-mongo-tools_mongod.zip bin/dcos-mongodb-healthcheck
