// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import api "github.com/percona/dcos-mongo-tools/common/api"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetEndpoint provides a mock function with given fields: endpointName
func (_m *Client) GetEndpoint(endpointName string) (*api.Endpoint, error) {
	ret := _m.Called(endpointName)

	var r0 *api.Endpoint
	if rf, ok := ret.Get(0).(func(string) *api.Endpoint); ok {
		r0 = rf(endpointName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Endpoint)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(endpointName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEndpoints provides a mock function with given fields:
func (_m *Client) GetEndpoints() (*api.Endpoints, error) {
	ret := _m.Called()

	var r0 *api.Endpoints
	if rf, ok := ret.Get(0).(func() *api.Endpoints); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Endpoints)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPodTasks provides a mock function with given fields: podName
func (_m *Client) GetPodTasks(podName string) ([]api.PodTask, error) {
	ret := _m.Called(podName)

	var r0 []api.PodTask
	if rf, ok := ret.Get(0).(func(string) []api.PodTask); ok {
		r0 = rf(podName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.PodTask)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(podName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPodURL provides a mock function with given fields:
func (_m *Client) GetPodURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPods provides a mock function with given fields:
func (_m *Client) GetPods() (*api.Pods, error) {
	ret := _m.Called()

	var r0 *api.Pods
	if rf, ok := ret.Get(0).(func() *api.Pods); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Pods)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
